language: node_js
node_js:
  - node
matrix:
  include:
    - os: osx
      addons:
        chrome: stable
        firefox: latest
        sudo: required
    - os: windows
      env: WINDOWS=true
      before_install:
        - choco install googlechrome
script:
  - npm start
cache: npm